# Generated by Django 3.2.19 on 2023-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_saloon', '0004_alter_review_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='title',
        ),
        migrations.AddField(
            model_name='master',
            name='speciality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
