# Generated by Django 3.2.19 on 2023-05-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_saloon', '0005_auto_20230527_1918'),
        ('beauty_saloon', '0005_auto_20230528_0930'),
    ]

    operations = [
    ]
